date.timezone = "Europe/Paris"
;file_uploads = On
;memory_limit = 64M
;upload_max_filesize = 64M
;post_max_size = 64M
;max_execution_time = 600

elastic_apm.server_url="https://apm-server.private.sfr.com"
elastic_apm.secret_token=""
elastic_apm.service_name="ENROLEMENT_SBD"
elastic_apm.environment="APP3567_EnrolementSBD"
;elastic_apm.log_level="DEBUG"